// <auto-generated />
using System;
using Application.Repository.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Application.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509194058_V24")]
    partial class V24
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Application.Core.Entities.Administrations", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Administrations");
                });

            modelBuilder.Entity("Application.Core.Entities.AdministrationsVacation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AdministrationId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AdministrationId");

                    b.ToTable("AdministrationsVacation");
                });

            modelBuilder.Entity("Application.Core.Entities.Assignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Assignment");
                });

            modelBuilder.Entity("Application.Core.Entities.ClassSubjectShare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShareAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("ClassSubjectShare");
                });

            modelBuilder.Entity("Application.Core.Entities.ClassSubjectTermWork", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<long>("WeekId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WeekId");

                    b.ToTable("ClassSubjectTermWork");
                });

            modelBuilder.Entity("Application.Core.Entities.Classes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<int>("ClassNumber")
                        .HasColumnType("int");

                    b.Property<int>("ClassType")
                        .HasColumnType("int");

                    b.Property<string>("FullId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Application.Core.Entities.DailySupervision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Monday")
                        .HasColumnType("bigint");

                    b.Property<long?>("Saturday")
                        .HasColumnType("bigint");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Sunday")
                        .HasColumnType("bigint");

                    b.Property<long?>("Thursday")
                        .HasColumnType("bigint");

                    b.Property<long?>("Tuseday")
                        .HasColumnType("bigint");

                    b.Property<long?>("Wednesday")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("Monday");

                    b.HasIndex("Saturday");

                    b.HasIndex("SchoolId");

                    b.HasIndex("Sunday");

                    b.HasIndex("Thursday");

                    b.HasIndex("Tuseday");

                    b.HasIndex("Wednesday");

                    b.ToTable("DailySupervision");
                });

            modelBuilder.Entity("Application.Core.Entities.ExamCodes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<decimal>("Result")
                        .HasColumnType("decimal(4,1)");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StudentId1")
                        .HasColumnType("bigint");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentId1");

                    b.HasIndex("SubjectId");

                    b.ToTable("ExamCodes");
                });

            modelBuilder.Entity("Application.Core.Entities.FinalScoresData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AppliedExam")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("Behavior")
                        .HasColumnType("decimal(4,1)");

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<string>("EducationalYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Exam")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("FinalExam")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("Homework")
                        .HasColumnType("decimal(4,1)");

                    b.Property<bool>("IsAppliedSaved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<decimal>("Review")
                        .HasColumnType("decimal(4,1)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("FinalScoresData");
                });

            modelBuilder.Entity("Application.Core.Entities.GeneralSupervision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TeacherId");

                    b.ToTable("GeneralSupervision");
                });

            modelBuilder.Entity("Application.Core.Entities.OutOfScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<long>("WeekId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("WeekId");

                    b.ToTable("OutOfScore");
                });

            modelBuilder.Entity("Application.Core.Entities.Punchments", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ConfirmedDate")
                        .HasColumnType("date");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("SeenDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("SendDate")
                        .HasColumnType("date");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Punchments");
                });

            modelBuilder.Entity("Application.Core.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AdminSelection")
                        .HasColumnType("bit");

                    b.Property<bool>("DirectorSelection")
                        .HasColumnType("bit");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("RoleArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SchoolSelection")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Application.Core.Entities.School", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AdministrationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SchoolMangerId")
                        .HasColumnType("bigint");

                    b.Property<int>("index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.HasKey("Id");

                    b.HasIndex("AdministrationId");

                    b.ToTable("School");
                });

            modelBuilder.Entity("Application.Core.Entities.SchoolVacation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("SchoolVacation");
                });

            modelBuilder.Entity("Application.Core.Entities.SendStudentToSchool", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanBeSend")
                        .HasColumnType("bit");

                    b.Property<long>("SchoolReceiverId")
                        .HasColumnType("bigint");

                    b.Property<long>("SchoolSenderId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SchoolReceiverId");

                    b.HasIndex("SchoolSenderId");

                    b.HasIndex("StudentId");

                    b.ToTable("SendStudentToSchool");
                });

            modelBuilder.Entity("Application.Core.Entities.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<int>("ExamTemplte")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HallNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsHome")
                        .HasColumnType("bit");

                    b.Property<string>("MargeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaceInHall")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PlaceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SchoolId2")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentAbsentCases", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsPatient")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentAbsentCases");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentAbsentData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<int>("ClassNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.Property<long>("WeekId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("WeekId");

                    b.ToTable("StudentAbsentData");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentClassGPA", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Activity")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("Behavior")
                        .HasColumnType("decimal(4,1)");

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Classwork")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("FirstExam")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("Homework")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("Missions")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("Oral")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("Review")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("SecondExam")
                        .HasColumnType("decimal(4,1)");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ThirdExam")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("TotalRate")
                        .HasColumnType("decimal(4,1)");

                    b.Property<long>("WeeKId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("WeeKId");

                    b.ToTable("StudentClassGPA");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentComplents", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ConfirmedDate")
                        .HasColumnType("date");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("SendDate")
                        .HasColumnType("date");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("StudentComplents");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentExamScoreData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AbsentSaved")
                        .HasColumnType("bit");

                    b.Property<decimal>("Behavior")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,1)")
                        .HasDefaultValue(0m);

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ExamResult")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,1)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSaved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("StudentExamScoreData");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentMonthlyCertificate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Activity")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("AllTotal")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("Behavior")
                        .HasColumnType("decimal(4,1)");

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Classwork")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("Exam")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("ExamBehavior")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("Homework")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("Missions")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("Oral")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("Review")
                        .HasColumnType("decimal(4,1)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(4,1)");

                    b.Property<bool>("UnderUpdate")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentMonthlyCertificate");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentMonthlyCertificateSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<bool>("StartCertificates")
                        .HasColumnType("bit");

                    b.Property<bool>("StartExam")
                        .HasColumnType("bit");

                    b.Property<long>("WeekId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("WeekId");

                    b.ToTable("StudentMonthlyCertificateSetting");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentScoreData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Activity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,1)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Behavior")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,1)")
                        .HasDefaultValue(0m);

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Classwork")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,1)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Homework")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,1)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("IsPreAbsent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSaved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<decimal>("Missions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,1)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Oral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,1)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Review")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,1)")
                        .HasDefaultValue(0m);

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint");

                    b.Property<long>("WeekId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("WeekId");

                    b.ToTable("StudentScoreData");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentScoreEdit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("StudentScoreDataId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentScoreDataId");

                    b.HasIndex("TeacherId");

                    b.ToTable("StudentScoreEdit");
                });

            modelBuilder.Entity("Application.Core.Entities.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("HasAppliedExam")
                        .HasColumnType("bit");

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("Application.Core.Entities.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanAccesControl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControlType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasQuiltyControl")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainPower")
                        .HasColumnType("bit");

                    b.Property<long?>("MainSubjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId2")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("TeacherTitleDate")
                        .HasColumnType("date");

                    b.Property<long?>("TeacherTitleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MainSubjectId");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId2");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TeacherTitleId");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("Application.Core.Entities.TeacherClasses", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherClasses");
                });

            modelBuilder.Entity("Application.Core.Entities.TeacherSupervisor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("SchoolId")
                        .HasColumnType("bigint");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherSupervisor");
                });

            modelBuilder.Entity("Application.Core.Entities.TeacherSupervisorSubjects", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeacherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherSupervisorSubjects");
                });

            modelBuilder.Entity("Application.Core.Entities.TeacherTitle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("ShareAmount1_2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ShareAmount3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ShareAmount4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeacherTitle");
                });

            modelBuilder.Entity("Application.Core.Entities.Week", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Week");
                });

            modelBuilder.Entity("Application.Core.Entities.AdministrationsVacation", b =>
                {
                    b.HasOne("Application.Core.Entities.Administrations", "Administration")
                        .WithMany("Vacations")
                        .HasForeignKey("AdministrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administration");
                });

            modelBuilder.Entity("Application.Core.Entities.Assignment", b =>
                {
                    b.HasOne("Application.Core.Entities.School", "School")
                        .WithMany("Assignments")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Teacher", "Teacher")
                        .WithMany("Assignments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Application.Core.Entities.ClassSubjectShare", b =>
                {
                    b.HasOne("Application.Core.Entities.Subject", "Subject")
                        .WithMany("ClassSubjectShares")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Application.Core.Entities.ClassSubjectTermWork", b =>
                {
                    b.HasOne("Application.Core.Entities.Week", "Week")
                        .WithMany()
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Week");
                });

            modelBuilder.Entity("Application.Core.Entities.Classes", b =>
                {
                    b.HasOne("Application.Core.Entities.School", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Application.Core.Entities.DailySupervision", b =>
                {
                    b.HasOne("Application.Core.Entities.Classes", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Teacher", "TMonday")
                        .WithMany()
                        .HasForeignKey("Monday")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Application.Core.Entities.Teacher", "TSaturday")
                        .WithMany()
                        .HasForeignKey("Saturday")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Application.Core.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Teacher", "TSunday")
                        .WithMany()
                        .HasForeignKey("Sunday")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Application.Core.Entities.Teacher", "TThursday")
                        .WithMany()
                        .HasForeignKey("Thursday")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Application.Core.Entities.Teacher", "TTuseday")
                        .WithMany()
                        .HasForeignKey("Tuseday")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Application.Core.Entities.Teacher", "TWednesday")
                        .WithMany()
                        .HasForeignKey("Wednesday")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Class");

                    b.Navigation("School");

                    b.Navigation("TMonday");

                    b.Navigation("TSaturday");

                    b.Navigation("TSunday");

                    b.Navigation("TThursday");

                    b.Navigation("TTuseday");

                    b.Navigation("TWednesday");
                });

            modelBuilder.Entity("Application.Core.Entities.ExamCodes", b =>
                {
                    b.HasOne("Application.Core.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Student", null)
                        .WithMany("ExamCodes")
                        .HasForeignKey("StudentId1");

                    b.HasOne("Application.Core.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Application.Core.Entities.FinalScoresData", b =>
                {
                    b.HasOne("Application.Core.Entities.Classes", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Application.Core.Entities.GeneralSupervision", b =>
                {
                    b.HasOne("Application.Core.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Application.Core.Entities.OutOfScore", b =>
                {
                    b.HasOne("Application.Core.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Week", "Week")
                        .WithMany()
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Subject");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("Application.Core.Entities.Punchments", b =>
                {
                    b.HasOne("Application.Core.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Application.Core.Entities.School", b =>
                {
                    b.HasOne("Application.Core.Entities.Administrations", "Administration")
                        .WithMany("Schools")
                        .HasForeignKey("AdministrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administration");
                });

            modelBuilder.Entity("Application.Core.Entities.SchoolVacation", b =>
                {
                    b.HasOne("Application.Core.Entities.School", "School")
                        .WithMany("Vacations")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Application.Core.Entities.SendStudentToSchool", b =>
                {
                    b.HasOne("Application.Core.Entities.School", "SchoolReceiver")
                        .WithMany()
                        .HasForeignKey("SchoolReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.School", "SchoolSender")
                        .WithMany()
                        .HasForeignKey("SchoolSenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolReceiver");

                    b.Navigation("SchoolSender");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Application.Core.Entities.Student", b =>
                {
                    b.HasOne("Application.Core.Entities.Classes", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Application.Core.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId");

                    b.Navigation("Class");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentAbsentCases", b =>
                {
                    b.HasOne("Application.Core.Entities.Student", "Student")
                        .WithMany("AbsentCases")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentAbsentData", b =>
                {
                    b.HasOne("Application.Core.Entities.Classes", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Student", "Student")
                        .WithMany("Absents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Application.Core.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Week", "Week")
                        .WithMany()
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentClassGPA", b =>
                {
                    b.HasOne("Application.Core.Entities.Classes", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Application.Core.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Week", "Week")
                        .WithMany()
                        .HasForeignKey("WeeKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentComplents", b =>
                {
                    b.HasOne("Application.Core.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("School");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentExamScoreData", b =>
                {
                    b.HasOne("Application.Core.Entities.Classes", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Student", "Student")
                        .WithMany("Exams")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentMonthlyCertificate", b =>
                {
                    b.HasOne("Application.Core.Entities.Classes", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentMonthlyCertificateSetting", b =>
                {
                    b.HasOne("Application.Core.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Week", "Week")
                        .WithMany()
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentScoreData", b =>
                {
                    b.HasOne("Application.Core.Entities.Classes", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Student", "Student")
                        .WithMany("Scores")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Application.Core.Entities.Week", "Week")
                        .WithMany()
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("Application.Core.Entities.StudentScoreEdit", b =>
                {
                    b.HasOne("Application.Core.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.StudentScoreData", "StudentScoreData")
                        .WithMany()
                        .HasForeignKey("StudentScoreDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Student");

                    b.Navigation("StudentScoreData");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Application.Core.Entities.Teacher", b =>
                {
                    b.HasOne("Application.Core.Entities.Subject", "MainSubject")
                        .WithMany()
                        .HasForeignKey("MainSubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Application.Core.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Role", "Role2")
                        .WithMany()
                        .HasForeignKey("RoleId2")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Application.Core.Entities.School", "School")
                        .WithMany("Teachers")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.TeacherTitle", "TeacherTitle")
                        .WithMany()
                        .HasForeignKey("TeacherTitleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MainSubject");

                    b.Navigation("Role");

                    b.Navigation("Role2");

                    b.Navigation("School");

                    b.Navigation("TeacherTitle");
                });

            modelBuilder.Entity("Application.Core.Entities.TeacherClasses", b =>
                {
                    b.HasOne("Application.Core.Entities.Classes", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Application.Core.Entities.TeacherSupervisor", b =>
                {
                    b.HasOne("Application.Core.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Application.Core.Entities.TeacherSupervisorSubjects", b =>
                {
                    b.HasOne("Application.Core.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Application.Core.Entities.TeacherSupervisor", "Teacher")
                        .WithMany("SubSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Application.Core.Entities.Administrations", b =>
                {
                    b.Navigation("Schools");

                    b.Navigation("Vacations");
                });

            modelBuilder.Entity("Application.Core.Entities.Classes", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Application.Core.Entities.School", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Classes");

                    b.Navigation("Teachers");

                    b.Navigation("Vacations");
                });

            modelBuilder.Entity("Application.Core.Entities.Student", b =>
                {
                    b.Navigation("AbsentCases");

                    b.Navigation("Absents");

                    b.Navigation("ExamCodes");

                    b.Navigation("Exams");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Application.Core.Entities.Subject", b =>
                {
                    b.Navigation("ClassSubjectShares");
                });

            modelBuilder.Entity("Application.Core.Entities.Teacher", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Application.Core.Entities.TeacherSupervisor", b =>
                {
                    b.Navigation("SubSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
